<?php

namespace AppBundle\Repository;

/**
 * choix_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class choix_userRepository extends \Doctrine\ORM\EntityRepository
{
}
