<?php

namespace AppBundle\Repository;

/**
 * messageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class messageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMessagesFromDiscussion($idDiscu){
        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder
            ->where('a.discussion_id = :discuId')
            ->setParameter('discuId', $idDiscu);
        //on récup la requête
        $query = $queryBuilder->getQuery();
        $res = $query->getResult();
        return $res;
    }
}
