<?php

namespace AppBundle\Repository;

/**
 * discussionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class noteRepository extends \Doctrine\ORM\EntityRepository
{
}

