<?php

namespace AppBundle\Repository;

/**
 * participant_discussionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class participant_discussionRepository extends \Doctrine\ORM\EntityRepository
{
}
