<?php

namespace AppBundle\Repository;
use AppBundle\Entity\discussion;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
    /*
     * @return discussion
     */
    public function findByDiscussion(discussion $discu){
        $queryBuilder = $this->createQueryBuilder('u');
        $queryBuilder
            ->where('u.discu_id != :id_discu')
            ->setParameter('id_discu', $discu)
            ->distinct();
        $query = $queryBuilder->getQuery();
        $res = $query->getResult();
        return $res;
    }


}
