<?php

namespace AppBundle\Repository;

/**
 * reunion_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reunion_userRepository extends \Doctrine\ORM\EntityRepository
{
}
