<?php

namespace AppBundle\Repository;

/**
 * sondage_projetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sondage_projetRepository extends \Doctrine\ORM\EntityRepository
{
}
