<?php

namespace AppBundle\Repository;

/**
 * user_chargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class user_chargeRepository extends \Doctrine\ORM\EntityRepository
{
}
